<?php

namespace Tests\Feature;

use App\Tweet;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var User
     */
    private $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();

        $this->user = factory(User::class)->create();
        Auth::loginUsingId($this->user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $tweetBody = 'Test tweet!';

        $this->post('/tweets', [
            'body' => $tweetBody
        ]);

        $tweets = Tweet::where('user_id', $this->user->id)->latest()->limit(1)->get();

        $this->assertEquals(1, Tweet::all()->count());
        $this->assertEquals($tweetBody, $tweets[0] ->body );
    }
}
